version: '3.8'

services:
  postgresql:
    image: postgres:15
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRESQLDB_ROOT_PASSWORD
      - POSTGRES_USER=$POSTGRESQLDB_USER
      - POSTGRES_DB=$POSTGRESQLDB_DATABASE
    ports:
      - $POSTGRESQLDB_LOCAL_PORT:$POSTGRESQLDB_DOCKER_PORT
  app:
    depends_on:
      - postgresql
    restart: on-failure
    image: nbubot-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url" : "jdbc:postgresql://postgresql:$POSTGRESQLDB_DOCKER_PORT/$POSTGRESQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
           "spring.datasource.username" : "$POSTGRESQLDB_USER",
           "spring.datasource.password" : "$POSTGRESQLDB_ROOT_PASSWORD",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
           "spring.jpa.hibernate.ddl-auto" : "validate",
           "telegram.bot.username" : "$TELEGRAM_BOT_USERNAME",
           "telegram.bot.token" : "$TELEGRAM_BOT_TOKEN"
         }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
